### ISSUE TITLE
RSpec 2.6.0 deprecation warning

### ISSUE THREAD

**Issue by searls** [rsim/ruby-plsql-spec#8] opened 2011-07-19 22:52 UTC
RSpec 2.6.0 is giving this warning when I run my specs:

    *****************************************************************
    DEPRECATION WARNING: you are using deprecated behaviour that will
    be removed from RSpec 3.

    You have set some configuration options after an example group has
    already been defined.  In RSpec 3, this will not be allowed.  All
    configuration should happen before the first example group is
    defined.  The configuration is happening at:

      /path/to/my/project/spec/spec_helper.rb:50
    *****************************************************************

This refers to this generated block:

    RSpec.configure do |config|
      config.before(:each) do
        database_connections.each do |name|
          plsql(name).savepoint "before_each"
        end
      end
      config.after(:each) do
        # Always perform rollback to savepoint after each test
        database_connections.each do |name|
          plsql(name).rollback_to "before_each"
        end
      end
      config.after(:all) do
        # Always perform rollback after each describe block
        database_connections.each do |name|
          plsql(name).rollback
        end
      end
    end

Thoughts?

**Comment by jgebal** [comment] 2015-06-24 00:15
Is it still valid after recent updates or can we close this one?

**Comment by jgebal** [comment] 2015-11-12 00:45
if we're unable to reproduce, and no one complains, can it be closed?

**Comment by javornikolov** [comment] 2015-11-14 13:12
I don't see warnings either, using rspec 3.4. I'm closing the issue...

**Closed by javornikolov** 2015-11-14 13:12 UTC
